made main exec cross-compatible. TODO: test on linux and add -h flag

diff --git a/passgen b/passgen
--- a/passgen
+++ b/passgen
@@ -1,14 +1,19 @@
-#!/bin/zsh
+#!/bin/bash
+shopt -s extglob
 
-file=$(mktemp)
+if ! find /usr/local/bin/ -name "*shred" &> /dev/null ;
+then
+    printf "\"(g)shred\" could not be found! \n Please install \"coreutils\" via your package manager."
+    exit
+fi
 
 generate () {
     if (( $1 > 0 && $1 <= 25 )) && (( $2 > 0 && $2 <= 50 )); then
-        touch $file; 
-        for i in {1..$2}
+        file=$(mktemp)
+        for i in $(seq 1 $2);
         do
-            head /dev/urandom | tr -dc A-Za-z0-9 | head -c $2 >> $file; 
-            echo "" >> $file;
+            head /dev/urandom | LC_CTYPE=C tr -dc A-Za-z0-9 | head -c $2 >> $file
+            echo "" >> $file
         done
         echo "Copy any of the generated passwords above and press 'q' to automatically delete this file." >> $file
         less $file;
@@ -22,9 +27,9 @@ generate () {
     fi
 }
 
-if [[ $# -eq 0 ]] then
+if [[ $# -eq 0 ]]; then
     generate 20 20
-elif ! [[ $1 =~ ^[0-9]+$ || $2 =~ ^[0-9]+$ ]] then
+elif ! [[ $1 =~ ^[0-9]+$ || $2 =~ ^[0-9]+$ ]]; then
     echo "Sorry, integers only"
 else
     generate $1 $2
